# Generated by Django 3.2.12 on 2024-12-12 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='valora',
        ),
        migrations.AddField(
            model_name='book',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
