# Generated by Django 3.2.12 on 2024-12-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_rename_rating_book_valora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('development', 'Permiso como Desarrollador'), ('scrum_master', 'Permiso como Scrum Master'), ('product_owner', 'Permiso como Product Owner')]},
        ),
    ]
