# Generated by Django 5.1.4 on 2024-12-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_fabricante_pais_producto_f_vencimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricante',
            name='pais',
            field=models.CharField(max_length=30),
        ),
    ]
