# Generated by Django 5.1.4 on 2024-12-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_f_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='f_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
