# Generated by Django 3.2.12 on 2024-12-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='rating',
            new_name='valora',
        ),
    ]
